# Generated by Django 3.0.7 on 2020-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posthog', '0071_cache_dashboard_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='slack_message_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='url_matching',
            field=models.CharField(blank=True, choices=[('contains', 'contains'), ('regex', 'regex'), ('exact', 'exact')], default='contains', max_length=400, null=True),
        ),
    ]
